version: '3.7'

services:
  postgres:
    build:
      context: ./images/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 5

